services:
  - type: web
    name: fastapi-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
    ports:
      - 8000

  - type: redis
    name: redis
    ipAllowList: [] # Empty means public access (optional)
    plan: free
